#!/bin/sh
# gen.sh - regenerate the two embedded data files for the typewriter command:
#   wubi_embed.c  - wubi.tab baked in as `wubi_tab[]` + `wubi_tab_len`
#   font_data.c   - a GNU Unifont bitmap subset covering ASCII + every hanzi
#                   that appears in wubi.tab (via gen_font.py)
#
# Reproducible: rerun after updating the table or unifont. The .tab comes from
# the wubi-fep repo (make tables there); unifont.hex from the GNU Unifont
# project (override paths with env vars below).
#
# ROM budget note: this board (gru_kevin) has an 8 MiB SPI flash and a binman
# layout that pins entries at fixed offsets, so the embedded data must stay
# small. The checked-in wubi.tab was trimmed to fit with:
#
#   (in ../wubi-fep)
#   python3 gen_table.py --scheme wubi --src wubi86.dict.yaml --out wubi.tab \
#           --top 20000 --max-phrases 20000
#
# That keeps the 20000 most-common hanzi/phrases (~4869 distinct glyphs) and
# yields ~0.6 MiB table + ~0.2 MiB font (~0.8 MiB embedded), down from ~3.1 MiB
# for the full dictionary. If you still overflow the ROM section or a fixed
# binman offset, trim harder (lower --top); to type rarer hanzi and you have
# room, raise it (distinct glyphs plateau around ~4900).
set -eu

HERE=$(dirname "$0")
TAB=${TAB:-"$HERE/../wubi-fep/wubi.tab"}
OUT=${OUT:-"$HERE/wubi_embed.c"}
UNIFONT_HEX=${UNIFONT_HEX:-"$HERE/unifont.hex"}
FONT_OUT=${FONT_OUT:-"$HERE/font_data.c"}

if [ ! -f "$TAB" ]; then
	echo "gen.sh: table not found: $TAB" >&2
	echo "  build it in wubi-fep first (make tables), or set TAB=." >&2
	exit 1
fi
if [ ! -f "$UNIFONT_HEX" ]; then
	echo "gen.sh: unifont not found: $UNIFONT_HEX" >&2
	echo "  fetch unifont.hex from unifoundry.com, or set UNIFONT_HEX=." >&2
	exit 1
fi

# --- 1. embed the wubi table ------------------------------------------------
python3 - "$TAB" "$OUT" <<'PY'
import sys
tab, out = sys.argv[1], sys.argv[2]
with open(tab, "rb") as f:
    data = f.read()
with open(out, "w") as f:
    f.write("/* Auto-generated by gen.sh - do not edit.\n")
    f.write(" * Wubi 86 IME table (%d bytes) compiled into U-Boot. */\n" % len(data))
    f.write('#include "wubi_embed.h"\n\n')
    f.write("const unsigned char wubi_tab[] = {\n")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        f.write("\t" + ",".join(str(b) for b in chunk) + ",\n")
    f.write("};\n")
    f.write("const unsigned long wubi_tab_len = sizeof(wubi_tab);\n")
print("embedded %d bytes -> %s" % (len(data), out))
PY

# --- 2. subset the font -----------------------------------------------------
python3 "$HERE/gen_font.py" --hex "$UNIFONT_HEX" --out "$FONT_OUT" "$TAB"
