#!/usr/bin/env python3
"""
Generate font_data.c: an embedded GNU Unifont bitmap subset covering exactly the
glyphs the typewriter command can display - printable ASCII plus every Unicode
codepoint that appears in the wubi .tab string pool.

Adapted from the coreboot-typewriter payload's gen_font.py. Unifont .hex format:
one glyph per line, `CODEPOINT:BITMAP` where BITMAP is hex, 16 rows. Narrow
glyphs => 16 bytes (8x16, 2 hex/row); wide (CJK) => 32 bytes (16x16, 4 hex/row).
Both are stored padded to 32 bytes/glyph with a width byte (8 or 16) so the C
side is uniform. Glyphs are emitted sorted by codepoint for binary search.

Usage:
    python3 gen_font.py --hex unifont.hex --out font_data.c wubi.tab
"""
import argparse
import struct
import sys

HDR_SIZE = 16
INDEX_ENTRIES = 26 * 26 + 1          # 677
IDX_SIZE = INDEX_ENTRIES * 4
CODE_LEN = 16                        # must match IME_CODE_LEN
RECORD_SIZE = CODE_LEN + 4 + 1 + 1   # code + off(u32) + wordLen(u8) + rank(u8)


def pool_codepoints(path):
    """Return the set of Unicode codepoints appearing in a .tab's string pool."""
    with open(path, "rb") as f:
        data = f.read()
    if data[:4] != b"IMET":
        sys.exit(f"{path}: bad magic")
    count, pool_bytes = struct.unpack_from("<II", data, 8)
    pool_start = HDR_SIZE + IDX_SIZE + count * RECORD_SIZE
    pool = data[pool_start:pool_start + pool_bytes]
    text = pool.decode("utf-8")
    return {ord(ch) for ch in text}


def load_unifont(path):
    """Parse unifont.hex -> {codepoint: (width, bytes[32])}."""
    glyphs = {}
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or ":" not in line:
                continue
            cp_s, bmp = line.split(":", 1)
            cp = int(cp_s, 16)
            raw = bytes.fromhex(bmp)
            if len(raw) == 16:          # 8x16 narrow
                width = 8
                padded = raw + b"\x00" * 16
            elif len(raw) == 32:        # 16x16 wide
                width = 16
                padded = raw
            else:
                continue                # skip exotic widths
            glyphs[cp] = (width, padded)
    return glyphs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--hex", required=True, help="path to unifont.hex")
    ap.add_argument("--out", required=True)
    ap.add_argument("tabs", nargs="+", help=".tab files to scan for codepoints")
    args = ap.parse_args()

    wanted = set(range(0x20, 0x7F))     # printable ASCII always
    for tab in args.tabs:
        wanted |= pool_codepoints(tab)

    unifont = load_unifont(args.hex)

    missing = 0
    entries = []
    for cp in sorted(wanted):
        g = unifont.get(cp)
        if g is None:
            missing += 1
            continue
        entries.append((cp, g[0], g[1]))

    with open(args.out, "w") as f:
        f.write("/* Auto-generated by gen_font.py - do not edit.\n")
        f.write(" * GNU Unifont bitmap subset for the typewriter command.\n")
        f.write(" * Each glyph: 16 rows; width 8 (narrow) or 16 (wide) px.\n")
        f.write(" * rows[] holds 16 rows x 2 bytes; narrow uses only the first\n")
        f.write(" * byte of each row, wide uses both. Sorted by cp. */\n")
        f.write('#include "font_data.h"\n\n')
        f.write("const struct tw_glyph tw_glyphs[] = {\n")
        for cp, width, raw in entries:
            b = ",".join(str(x) for x in raw)
            f.write(f"\t{{0x{cp:04X},{width},{{{b}}}}},\n")
        f.write("};\n")
        f.write(f"const unsigned tw_glyphs_count = {len(entries)};\n")

    print(f"font: {len(entries)} glyphs -> {args.out} "
          f"({missing} wanted codepoints had no unifont glyph)")


if __name__ == "__main__":
    sys.exit(main())
